@startuml
left to right direction

namespace MediaPlayer {

    enum ClientState {
        MainUserSelect
        GeneralSelect
        FriendSelect
        Stopped
    }
    
    class Client {
        - _mainUser: User
        - _currentSong: Song
        - _player: WaveOutEvent
        - _audioReader: AudioFileReader
        - _queue: Queue<Song>
        - _state: ClientState
        
        + Start()
        
        ' commands
        - AppendQueue(song: Song): void
        - PlaySong(song: Song): void
        - SkipSong(): void
        - TogglePause(): void
        - StopPlayer(): void
        
        ' state
        - MainUserSelect(): void
        - GeneralSelect(): void
        - FriendSelect():  void
        
        ' menus
        - SongSelectMenu(): Song
        - UserSelectMenu(): User
        - PlaylistSelectMenu(user: User): Playlist
        
        ' helpers
        - FlushTerminal(): void
        - Input(allowedChars: char[1..*]): char
    }
    
    namespace Entities {
    
        class Song {
            - _name: string
            - _artists: List<Artist>
            - _duration: double
            - _releaseDate: DateOnly
            + Name: _name
            + Artists: _artist
            + Duration: _duration
            + ReleaseDate: _releaseDate
            
            + GetAllSongs(): List<Song> {static}
        }
            
        class User {
            - _name: string
            - _friends: List<User>
            - _playlists: List<Playlist>
            + Name: _name
            + Friends: _friends
            + Playlists: _playlists
            
            + GetAllUsers(): List<User> {static}
        }
        
        class Playlist {
            - _name: string
            - _songs: List<Song>
            + Name: _name
            + Songs: _songs
            
            + Add(song: Song)
            + Remove(index: int)
            + Rename(newName: string)
        }
        
        class Album {
            - _name: string
            - _artists: List<Artist>
            - _songs: List<Song>
            + Name: _name
            + Artists: _artists
            + Songs: _songs
            
            + GetAllAlbums(): List<Album> {static}
        }
        
        class Artist {
            - _name: string
            - _albums: List<Album>
            - _songs: List<Song>
            + Albums: _albums
            + Songs: _songs
            + Name: _name
            
            + GetAllArtists(): List<Artists> {static}
        }
    }
}

Client --> User : mainUser
Client --> Song : currentSong
Client --> "0..*" Song : queue
Client --> ClientState : state

User o-- "0..*" Playlist : playlists
User --> "0..*" User : friends

Album --> "1..*" Song : songs
Album -- "1..*" Artist : artists

Playlist --> "0..*" Song : songs

Song -- "1..*" Artist : artists

@enduml