@startuml

class Client {
    + Stop()
    + Play()
}

class Song {
    - _title: string
    + Title: _title
    - _artist: Artist
    - _duration: double
}

class User {
    - _name: string
    + Name: _name
    + Playlist: Playlist
}

class Playlist {
    - _name: string
    - _songAmount: int
    - _duration: double
}

class Album {
    - _artist: Artist
    - _name: string
    - _songAmount: int
    - _duration: double
} 

class Artist {
    - _name: string
    - _albums: Album
    - _songs: Song
}

@enduml