@startuml
[*] --> MainUserSelect
state MainUserSelect : laat hoofdgebruikers zien
state MainUserSelect : wacht op hoofdgebruiker keuze
MainUserSelect --> MainUserSelect : kiest een ongeldige optie
MainUserSelect --> GeneralSelect : kiest hoofdgebruiker
state GeneralSelect : laat opties zien van wat gebruikers kunnen doen
state GeneralSelect : wacht op selectie keuze
GeneralSelect --> GeneralSelect : kiest een ongeldige optie
GeneralSelect --> MainUserSelect : Uitloggen
GeneralSelect --> GeneralSelect : help
GeneralSelect --> AlbumSelectMenu : Albums
GeneralSelect --> PlaylistSelectMenu : Afspeelijsten
GeneralSelect --> SongSelectMenu : Nummers
GeneralSelect --> FriendSelect : Vrienden
FriendSelect --> GeneralSelect : Terug
state AlbumSelectMenu : Laat een album lijst inzien
state AlbumSelectMenu : album kan gekozen worden
state AlbumSelectMenu : gebruiker kan terug gaan om de album lijst in te zien
AlbumSelectMenu --> GeneralSelect : Terug
state FriendSelect : Laat vrienden zien
state FriendSelect : Laat geef optie om vrienden toe te voegen
state FriendSelect : Wacht op gebruikers vriend verzoek
GeneralSelect --> Stopped : stop
state Stopped : Applicatie is gestopt
@enduml